name: spraay
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  smooth_page_indicator: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  pin_code_fields: ^8.0.1
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  cherry_toast: ^1.3.1
  barcode_widget: ^2.0.4
  screenshot: ^2.1.0
  path_provider: ^2.1.0
  share_plus: ^7.1.0
  url_launcher: ^6.1.12
  whatsapp_unilink: ^2.1.0
  dotted_border: ^2.0.0+3
  image_picker: ^1.0.2
  fl_chart: ^0.64.0
  qr_flutter: ^4.1.0
  fluttertoast: ^8.2.2
#  contacts_service: ^0.6.3
  permission_handler: ^11.0.1
  lottie: ^2.6.0
  appinio_swiper: ^2.0.2
  flutter_animate: ^4.2.0+1
  fluttercontactpicker: ^4.7.0
  local_auth: ^2.1.6
  loading_overlay: ^0.3.0
  http: ^1.1.0
  flutter_udid: ^2.0.1
  circular_profile_avatar: ^2.0.5
  google_maps_flutter: ^2.5.0
  uuid: ^4.1.0
  geocoding: ^2.1.0
  local_session_timeout: ^2.3.0
  open_mail_app: ^0.4.5
  document_file_save_plus: ^2.0.0
  flutter_secure_storage: ^9.0.0
  flutter_rounded_date_picker: ^3.0.4
#  flutter_media_downloader: ^0.0.1

#  overlay_loader_with_app_icon: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/
     - images/mark_pin.png
     - images/mark_pinn.png

  fonts:
     - family: Bold
       fonts:
         - asset: fonts/DMSans-Bold.ttf
     - family: Medium
       fonts:
         - asset: fonts/DMSans-Medium.ttf
     - family: Regular
       fonts:
         - asset: fonts/DMSans-Regular.ttf
     - family: SemiBold
       fonts:
         - asset: fonts/DMSans-SemiBold.ttf

     - family: PlusJakartaSans
       fonts:
         - asset: fonts/PlusJakartaSans-Bold.ttf
     - family: SemiPlusJakartaSans
       fonts:
         - asset: fonts/PlusJakartaSans-SemiBold.ttf
     - family: LightPlusJakartaSans
       fonts:
         - asset: fonts/PlusJakartaSans-Light.ttf


