// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ypFqeJcnXzJDKEidonhHCUB0a_2ynwc',
    appId: '1:45187346066:web:db6defd9660ce714a1804b',
    messagingSenderId: '45187346066',
    projectId: 'spraay-app',
    authDomain: 'spraay-app.firebaseapp.com',
    storageBucket: 'spraay-app.appspot.com',
    measurementId: 'G-BPPLNV2Q46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfLRwrtOHm_jg7cUkOdZr2ubfNkFTbR1E',
    appId: '1:45187346066:android:deb8c57478735fc3a1804b',
    messagingSenderId: '45187346066',
    projectId: 'spraay-app',
    storageBucket: 'spraay-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg9wbTR3Eu_L-SkbY3SPQ5Aj8aXtaG3yM',
    appId: '1:45187346066:ios:999e1dbb36e5e49fa1804b',
    messagingSenderId: '45187346066',
    projectId: 'spraay-app',
    storageBucket: 'spraay-app.appspot.com',
    iosBundleId: 'com.spraay.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg9wbTR3Eu_L-SkbY3SPQ5Aj8aXtaG3yM',
    appId: '1:45187346066:ios:85c6a96d4761f3a8a1804b',
    messagingSenderId: '45187346066',
    projectId: 'spraay-app',
    storageBucket: 'spraay-app.appspot.com',
    iosBundleId: 'com.app.spraay.RunnerTests',
  );
}
