class Autogenerated {
  bool? success;
  num? code;
  List<SingleGiftCardModel>? data;
  String? message;

  Autogenerated({this.success, this.code, this.data, this.message});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    code = json['code'];
    if (json['data'] != null) {
      data = <SingleGiftCardModel>[];
      json['data'].forEach((v) {
        data!.add(new SingleGiftCardModel.fromJson(v));
      });
    }
    message = json['message'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['message'] = this.message;
    return data;
  }
}

class SingleGiftCardModel {
  num? productId;
  String? productName;
  bool? global;
  bool? supportsPreOrder;
  num? senderFee;
  num? senderFeePercentage;
  num? discountPercentage;
  String? denominationType;
  String? recipientCurrencyCode;
  num? minRecipientDenomination;
  num? maxRecipientDenomination;
  String? senderCurrencyCode;
  num? minSenderDenomination;
  num? maxSenderDenomination;
  List<num>? fixedRecipientDenominations;
  List<num?>? fixedSenderDenominations;
  Map<dynamic, dynamic>? fixedRecipientToSenderDenominationsMap;
  Map<dynamic, dynamic>? metadata;
  List<String>? logoUrls;
  Brand? brand;
  Category? category;
  Country? country;
  RedeemInstruction? redeemInstruction;

  SingleGiftCardModel(
      {this.productId,
      this.productName,
      this.global,
      this.supportsPreOrder,
      this.senderFee,
      this.senderFeePercentage,
      this.discountPercentage,
      this.denominationType,
      this.recipientCurrencyCode,
      this.minRecipientDenomination,
      this.maxRecipientDenomination,
      this.senderCurrencyCode,
      this.minSenderDenomination,
      this.maxSenderDenomination,
      this.fixedRecipientDenominations,
      this.fixedSenderDenominations,
      this.fixedRecipientToSenderDenominationsMap,
      this.metadata,
      this.logoUrls,
      this.brand,
      this.category,
      this.country,
      this.redeemInstruction});

  SingleGiftCardModel.fromJson(Map<String, dynamic> json) {
    productId = json['productId'];
    productName = json['productName'];
    global = json['global'];
    supportsPreOrder = json['supportsPreOrder'];
    senderFee = json['senderFee'];
    senderFeePercentage = json['senderFeePercentage'];
    discountPercentage = json['discountPercentage'];
    denominationType = json['denominationType'];
    recipientCurrencyCode = json['recipientCurrencyCode'];
    minRecipientDenomination = json['minRecipientDenomination'];
    maxRecipientDenomination = json['maxRecipientDenomination'];
    senderCurrencyCode = json['senderCurrencyCode'];
    minSenderDenomination = json['minSenderDenomination'];
    maxSenderDenomination = json['maxSenderDenomination'];
    fixedRecipientDenominations =
        List<num>.from(json["fixedRecipientDenominations"].map((x) => x));
    fixedSenderDenominations = json["fixedSenderDenominations"] == null
        ? []
        : List<num>.from(json["fixedSenderDenominations"]!.map((x) => x));
    // fixedRecipientDenominations = json['fixedRecipientDenominations'] != null
    //     ? json['fixedRecipientDenominations'].cast<num?>()
    //     : null;
    // fixedSenderDenominations = json['fixedSenderDenominations'] != null
    //     ? json['fixedSenderDenominations'].cast<num?>()
    //     : null;
    // print(
    //     "fixedSenderDenominations::::${json['fixedSenderDenominations']}| ${json['fixedSenderDenominations'].runtimeType} ");
    // print(
    //     "fixedRecipientDenominations:::${json['fixedRecipientDenominations']} | ${json['fixedRecipientDenominations'].runtimeType}");
    fixedRecipientToSenderDenominationsMap =
        json['fixedRecipientToSenderDenominationsMap'] != null
            ? json['fixedRecipientToSenderDenominationsMap']
            : null;
    metadata = json['metadata'] != null ? json['metadata'] : null;
    logoUrls = json['logoUrls'].cast<String>();
    brand = json['brand'] != null ? new Brand.fromJson(json['brand']) : null;
    category = json['category'] != null
        ? new Category.fromJson(json['category'])
        : null;
    country =
        json['country'] != null ? new Country.fromJson(json['country']) : null;
    redeemInstruction = json['redeemInstruction'] != null
        ? new RedeemInstruction.fromJson(json['redeemInstruction'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['productId'] = this.productId;
    data['productName'] = this.productName;
    data['global'] = this.global;
    data['supportsPreOrder'] = this.supportsPreOrder;
    data['senderFee'] = this.senderFee;
    data['senderFeePercentage'] = this.senderFeePercentage;
    data['discountPercentage'] = this.discountPercentage;
    data['denominationType'] = this.denominationType;
    data['recipientCurrencyCode'] = this.recipientCurrencyCode;
    data['minRecipientDenomination'] = this.minRecipientDenomination;
    data['maxRecipientDenomination'] = this.maxRecipientDenomination;
    data['senderCurrencyCode'] = this.senderCurrencyCode;
    data['minSenderDenomination'] = this.minSenderDenomination;
    data['maxSenderDenomination'] = this.maxSenderDenomination;
    data['fixedRecipientDenominations'] = this.fixedRecipientDenominations;
    data['fixedSenderDenominations'] = this.fixedSenderDenominations;
    if (this.fixedRecipientToSenderDenominationsMap != null) {
      data['fixedRecipientToSenderDenominationsMap'] =
          this.fixedRecipientToSenderDenominationsMap;
    }
    if (this.metadata != null) {
      data['metadata'] = this.metadata;
    }
    data['logoUrls'] = this.logoUrls;
    if (this.brand != null) {
      data['brand'] = this.brand!.toJson();
    }
    if (this.category != null) {
      data['category'] = this.category!.toJson();
    }
    if (this.country != null) {
      data['country'] = this.country!.toJson();
    }
    if (this.redeemInstruction != null) {
      data['redeemInstruction'] = this.redeemInstruction!.toJson();
    }
    return data;
  }

  @override
  String toString() {
    return 'SingleGiftCardModel{productId: $productId, productName: $productName, global: $global, supportsPreOrder: $supportsPreOrder, senderFee: $senderFee, senderFeePercentage: $senderFeePercentage, discountPercentage: $discountPercentage, denominationType: $denominationType, recipientCurrencyCode: $recipientCurrencyCode, minRecipientDenomination: $minRecipientDenomination, maxRecipientDenomination: $maxRecipientDenomination, senderCurrencyCode: $senderCurrencyCode, minSenderDenomination: $minSenderDenomination, maxSenderDenomination: $maxSenderDenomination, fixedRecipientDenominations: $fixedRecipientDenominations, fixedSenderDenominations: $fixedSenderDenominations, fixedRecipientToSenderDenominationsMap: $fixedRecipientToSenderDenominationsMap, metadata: ${metadata.toString()}, logoUrls: $logoUrls, brand: ${brand.toString()}, category: ${category.toString()}, country: ${country.toString()}, redeemInstruction: ${redeemInstruction.toString()}}';
  }
}

class Brand {
  num? brandId;
  String? brandName;

  Brand({this.brandId, this.brandName});

  Brand.fromJson(Map<String, dynamic> json) {
    brandId = json['brandId'];
    brandName = json['brandName'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['brandId'] = this.brandId;
    data['brandName'] = this.brandName;
    return data;
  }

  @override
  String toString() {
    return 'Brand{brandId: $brandId, brandName: $brandName}';
  }
}

class Category {
  num? id;
  String? name;

  Category({this.id, this.name});

  Category.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }

  @override
  String toString() {
    return 'Category{id: $id, name: $name}';
  }
}

class Country {
  String? isoName;
  String? name;
  String? flagUrl;

  Country({this.isoName, this.name, this.flagUrl});

  Country.fromJson(Map<String, dynamic> json) {
    isoName = json['isoName'];
    name = json['name'];
    flagUrl = json['flagUrl'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['isoName'] = this.isoName;
    data['name'] = this.name;
    data['flagUrl'] = this.flagUrl;
    return data;
  }

  @override
  String toString() {
    return 'Country{isoName: $isoName, name: $name, flagUrl: $flagUrl}';
  }
}

class RedeemInstruction {
  String? concise;
  String? verbose;

  RedeemInstruction({this.concise, this.verbose});

  RedeemInstruction.fromJson(Map<String, dynamic> json) {
    concise = json['concise'];
    verbose = json['verbose'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['concise'] = this.concise;
    data['verbose'] = this.verbose;
    return data;
  }

  @override
  String toString() {
    return 'RedeemInstruction{concise: $concise, verbose: $verbose}';
  }
}
